spring:
  application:
    name: cards-api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      "[hibernate.format_sql]": true
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: Nave@0596
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9091
  # servlet:
  #   context-path: /tracker
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
